# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4e062d054f4a356451872487f69e49f16245bc5d17e7a251882e4f4937f279480e207230babef5333d2bd5065c5681c0b20edfc563331bd0bb75258807b167a5

test:
  secret_key_base: 00e2ef2308bb84982a39df934ba76c80bc16b3addca2b15ce3ca27452ca52542ba084c752713308f6bff20a8c05206c7bbfdc08edb22bfb07a1d548c8d39cd43

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
